// <auto-generated />
using System;
using BYCS.Infraestructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RRHH.Migrations
{
    [DbContext(typeof(BYCS_DBContext))]
    [Migration("20260505014609_m61")]
    partial class m61
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BYCS.Core.Models.Correo", b =>
                {
                    b.Property<int>("id_correo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_correo"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_correo");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Informe", b =>
                {
                    b.Property<int>("id_informe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_informe"));

                    b.Property<string>("codigo_informe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_informe");

                    b.HasIndex("codigo_informe")
                        .IsUnique();

                    b.ToTable("Informes");
                });

            modelBuilder.Entity("BYCS.Core.Models.Inventario", b =>
                {
                    b.Property<int>("id_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_inventario"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_inventario");

                    b.HasIndex("codigo")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("BYCS.Core.Models.Item", b =>
                {
                    b.Property<int>("id_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_item"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_item");

                    b.HasIndex("codigo")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BYCS.Core.Models.ItemStock", b =>
                {
                    b.Property<int>("id_item")
                        .HasColumnType("integer");

                    b.Property<int>("id_inventario")
                        .HasColumnType("integer");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("codigo_inventario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigo_item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_item", "id_inventario");

                    b.HasIndex("id_inventario");

                    b.HasIndex("codigo_item", "codigo_inventario")
                        .IsUnique();

                    b.ToTable("ItemStocks");
                });

            modelBuilder.Entity("BYCS.Core.Models.Protocolo", b =>
                {
                    b.Property<int>("id_protocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_protocolo"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_protocolo");

                    b.HasIndex("codigo")
                        .IsUnique();

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Respuesta", b =>
                {
                    b.Property<int>("id_solicitud")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<bool>("aprobado")
                        .HasColumnType("boolean");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigo_solicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_solicitud", "id_usuario", "fecha");

                    b.HasIndex("id_usuario");

                    b.HasIndex("codigo_solicitud", "ci")
                        .IsUnique();

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("BYCS.Core.Models.RespuestaInforme", b =>
                {
                    b.Property<int>("id_solicitud")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<int>("id_informe")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Respuestafecha")
                        .HasColumnType("date");

                    b.Property<int?>("Respuestaid_solicitud")
                        .HasColumnType("integer");

                    b.Property<int?>("Respuestaid_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigo_informe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigo_solicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.HasKey("id_solicitud", "id_usuario", "id_informe");

                    b.HasIndex("id_informe");

                    b.HasIndex("Respuestaid_solicitud", "Respuestaid_usuario", "Respuestafecha");

                    b.HasIndex("codigo_solicitud", "ci", "codigo_informe")
                        .IsUnique();

                    b.ToTable("RespuestaInformes");
                });

            modelBuilder.Entity("BYCS.Core.Models.Solicitud", b =>
                {
                    b.Property<int>("id_solicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_solicitud"));

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_solicitud");

                    b.HasIndex("codigo")
                        .IsUnique();

                    b.HasIndex("id_usuario");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("BYCS.Core.Models.SolicitudProtocolo", b =>
                {
                    b.Property<int>("id_protocolo")
                        .HasColumnType("integer");

                    b.Property<int>("id_solicitud")
                        .HasColumnType("integer");

                    b.Property<string>("codigo_protocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigo_solicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("fecha_fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.HasKey("id_protocolo", "id_solicitud");

                    b.HasIndex("id_solicitud");

                    b.HasIndex("codigo_protocolo", "codigo_solicitud", "fecha_inicio")
                        .IsUnique();

                    b.ToTable("SolicitudProtocolos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Telefono", b =>
                {
                    b.Property<int>("id_telefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_telefono"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_telefono");

                    b.HasIndex("telf")
                        .IsUnique();

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("apellido_m")
                        .HasColumnType("text");

                    b.Property<string>("apellido_p")
                        .HasColumnType("text");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.HasIndex("ci")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BYCS.Core.Models.UsuarioCorreo", b =>
                {
                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<int>("id_correo")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("fecha_fin")
                        .HasColumnType("date");

                    b.HasKey("id_usuario", "id_correo", "fecha_inicio");

                    b.HasIndex("id_correo");

                    b.HasIndex("ci", "correo", "fecha_inicio")
                        .IsUnique();

                    b.ToTable("UsuarioCorreos");
                });

            modelBuilder.Entity("BYCS.Core.Models.UsuarioTelefono", b =>
                {
                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<int>("id_telefono")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("fecha_fin")
                        .HasColumnType("date");

                    b.Property<string>("telf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario", "id_telefono", "fecha_inicio");

                    b.HasIndex("id_telefono");

                    b.HasIndex("ci", "telf", "fecha_inicio")
                        .IsUnique();

                    b.ToTable("UsuarioTelefonos");
                });

            modelBuilder.Entity("BYCS.Core.Models.ItemStock", b =>
                {
                    b.HasOne("BYCS.Core.Models.Inventario", "Inventario")
                        .WithMany("StockItems")
                        .HasForeignKey("id_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYCS.Core.Models.Item", "Item")
                        .WithMany("StockItems")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BYCS.Core.Models.Respuesta", b =>
                {
                    b.HasOne("BYCS.Core.Models.Solicitud", "Solicitud")
                        .WithMany("Respuestas")
                        .HasForeignKey("id_solicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYCS.Core.Models.Usuario", "Usuario")
                        .WithMany("Respuestas")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BYCS.Core.Models.RespuestaInforme", b =>
                {
                    b.HasOne("BYCS.Core.Models.Informe", null)
                        .WithMany("RespuestaInformes")
                        .HasForeignKey("id_informe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYCS.Core.Models.Respuesta", null)
                        .WithMany("RespuestaInformes")
                        .HasForeignKey("Respuestaid_solicitud", "Respuestaid_usuario", "Respuestafecha");
                });

            modelBuilder.Entity("BYCS.Core.Models.Solicitud", b =>
                {
                    b.HasOne("BYCS.Core.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BYCS.Core.Models.SolicitudProtocolo", b =>
                {
                    b.HasOne("BYCS.Core.Models.Protocolo", "Protocolo")
                        .WithMany("SolicitudProtocolos")
                        .HasForeignKey("id_protocolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYCS.Core.Models.Solicitud", "Solicitud")
                        .WithMany("SolicitudProtocolos")
                        .HasForeignKey("id_solicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocolo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("BYCS.Core.Models.UsuarioCorreo", b =>
                {
                    b.HasOne("BYCS.Core.Models.Correo", "Correo")
                        .WithMany("UsuarioCorreos")
                        .HasForeignKey("id_correo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYCS.Core.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correo");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("BYCS.Core.Models.UsuarioTelefono", b =>
                {
                    b.HasOne("BYCS.Core.Models.Telefono", "Telefono")
                        .WithMany("UsuarioTelefonos")
                        .HasForeignKey("id_telefono")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYCS.Core.Models.Usuario", "usuario")
                        .WithMany("UsuarioTelefonos")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telefono");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("BYCS.Core.Models.Correo", b =>
                {
                    b.Navigation("UsuarioCorreos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Informe", b =>
                {
                    b.Navigation("RespuestaInformes");
                });

            modelBuilder.Entity("BYCS.Core.Models.Inventario", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("BYCS.Core.Models.Item", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("BYCS.Core.Models.Protocolo", b =>
                {
                    b.Navigation("SolicitudProtocolos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Respuesta", b =>
                {
                    b.Navigation("RespuestaInformes");
                });

            modelBuilder.Entity("BYCS.Core.Models.Solicitud", b =>
                {
                    b.Navigation("Respuestas");

                    b.Navigation("SolicitudProtocolos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Telefono", b =>
                {
                    b.Navigation("UsuarioTelefonos");
                });

            modelBuilder.Entity("BYCS.Core.Models.Usuario", b =>
                {
                    b.Navigation("Respuestas");

                    b.Navigation("Solicitudes");

                    b.Navigation("UsuarioTelefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
